brew "git"
brew "node"
brew "pnpm"
brew "python"
brew "baobab"
brew "black"
brew "tree"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "ghostty"
cask "obsidian"
cask "visual-studio-code"
